### PR TITLE
Team 1 : Login page 

### PR DESCRIPTION
**Pull request by samaritan-mt**
- Created login component with tested authentication with the firebase SDK 
- User input sanitizing to avoid Cross Site Scripting
- Basic Error handling (planning to transform it into a matdialog instead of an alert)
- Removed the basic HTML place holder of app component (because it serves no purpose) 
- Redirection to the registration page with the sign up button 
- Commented and documented code for better understanding

### CODE REVIEW

**Comment by samaritan-mt** [comment]
The github PR preview is a blank page because of the removal of the main app component template (that is useless if we start routing) go to login page with login route

**Review by Hendercraft — APPROVED** [review]
Seems good to me, the login works

I know the route aren't implemented yet, but the sign-up button thow an error in the console
```
ERROR Error: Uncaught (in promise): Error: NG04002
x@https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1:16955
noMatchError@https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1:182428
621/recognize/<@https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1:182713
621/Ao/</i<@https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1:146749
621/wG/this._error<@https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1:8026
error@https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1:2960
_error@https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1:3200
error@https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1:2960
_error@https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5…
    z https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    z https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    ee https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    invokeTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    onInvokeTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    invokeTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    runTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    _ https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    invokeTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    O https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    N https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    B https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    t https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    scheduleTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    onScheduleTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    scheduleTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    scheduleTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    scheduleEventTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    u https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    toPromise https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    t https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    toPromise https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    m0 https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    jF https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    s https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    T https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    t https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    T https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    iV https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    Sre https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    Sre https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    jF https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    s https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    invoke https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    onInvoke https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    invoke https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    run https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    ee https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    invokeTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    onInvokeTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    invokeTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    runTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    _ https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    promise callback*q https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    R https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    scheduleTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    onScheduleTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    scheduleTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    scheduleTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    scheduleMicroTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    ee https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    z https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    I https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    P https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    promise callback*332/</C/l.prototype.then/< https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    t https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    then https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    z https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    resolve https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    jF https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    s https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    invoke https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    onInvoke https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    invoke https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    run https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    ee https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    invokeTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    onInvokeTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    invokeTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    runTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    _ https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    promise callback*q https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    R https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    scheduleTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    onScheduleTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    scheduleTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    scheduleTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    scheduleMicroTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    ee https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    z https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    I https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    P https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    promise callback*332/</C/l.prototype.then/< https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    t https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
[main.13ae97229a5af80f.js:1:57459](https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js)
    handleError https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    next https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    next https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    _next https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    next https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    next https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    ef https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    next https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    emit https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    onHandleError https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    invoke https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    run https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    runOutsideAngular https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    onHandleError https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    handleError https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    runGuarded https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    microtaskDrainDone https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    _ https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    invokeTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    O https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    N https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    B https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    (Asynchrone : EventListener.handleEvent)
    t https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    scheduleTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    onScheduleTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    scheduleTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    scheduleTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    scheduleEventTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    u https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    toPromise https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    t https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    toPromise https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    m0 https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    jF https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    s https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    T https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    t https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    T https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    iV https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    Sre https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    Sre https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    jF https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    s https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    invoke https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    onInvoke https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    invoke https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    run https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    ee https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    invokeTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    onInvokeTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    invokeTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    runTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    _ https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    (Asynchrone : promise callback)
    q https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    R https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    scheduleTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    onScheduleTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    scheduleTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    scheduleTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    scheduleMicroTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    ee https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    z https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    I https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    P https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    (Asynchrone : promise callback)
    then https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    t https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    then https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    z https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    resolve https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    jF https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    s https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    invoke https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    onInvoke https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    invoke https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    run https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    ee https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    invokeTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    onInvokeTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/main.13ae97229a5af80f.js:1
    invokeTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    runTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    _ https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    (Asynchrone : promise callback)
    q https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    R https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    scheduleTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    onScheduleTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    scheduleTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    scheduleTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    scheduleMicroTask https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    ee https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    z https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    I https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    P https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    (Asynchrone : promise callback)
    then https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    t https://agilebackend-9e4d6--pr24-dev-login-team1-7hrgzl22.web.app/polyfills.13979b31c8d77955.js:1
    ```
    Don't really know what to make of it, but since it actually serve no purpose for now seems good

**Comment by samaritan-mt** [comment]
The error is thrown because the route of the signup button is unknown to the component. Sign Up button on click normally sends you directly to the registration route but since it is not implemented I didn't add it to the app-routing-module.ts. I don't know why the error is obfuscated though on the PR request page because on my browser with the project it throws an unknown route error.

**Review by BenjaminCDP — APPROVED** [review]
I have tested your login component guys, great work ! Everything works and looks good too. I have some remarks though, as stated in Angular doc here : https://angular.io/guide/security is implying that everything is sanitize by default, so your sanitize function might be an overhead, as the value will still be treated as untrusted by Angular. Moreover, I think you used Template driven forms as stated here : https://angular.io/guide/forms-overview#choosing-an-approach, sure it works but it would be better to use Reactive forms, we might want to revisit this later if we have time. In any case, still a great job.

**Comment by samaritan-mt** [comment]
No problem for the ReactiveForms I'll make the switch as soon as possible I didn't read a lot about the approaches to forms before. As for te input sanitizing, it's only about escaping special characters it's not a complete security measure as security is not part of our backlog more of a salt on the hash (ba dum tss) for our login form.

**Pull request merged**
