### PR TITLE
Dev team1 login bug fixed

### PR DESCRIPTION
**Pull request by samaritan-mt**
Switched Login forms to Reactive forms and various routes fix.

### CODE REVIEW

**Comment by samaritan-mt** [comment]
I resolved the merge conflict in app-routing-module.ts by keeping both chunks of conflicting code (not the worst conflict in the history)

**Comment by samaritan-mt** [comment]
I'll add a guard on the page before you approve this PR

**Review by BenjaminCDP — APPROVED** [review]
Perfect !

**Comment by Hendercraft** [comment]
> I'll add a guard on the page before you approve this PR

Nice, i'll approve it once you added the guard

**Comment by samaritan-mt** [comment]
Hello Guys, For the guard is it enough for the moment to only add the canActivate attribute on the Login Component route or do you want to implement checks ?

**Review by Hendercraft — APPROVED** [review]

**Review by BenjaminCDP — APPROVED** [review]

**Review by Nellou90 — APPROVED** [review]

**Pull request merged**
